name: daily_reset_app
description: A daily checklist app with 3 AM reset and optional notifications
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  intl: ^0.19.0
  flutter_timezone: ^3.0.0
  google_fonts: ^6.1.0
  confetti: ^0.7.0
  home_widget: ^0.7.0
  table_calendar: ^3.1.2
  flutter_reorderable_grid_view: ^5.5.2
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.jpg
